- pam-u2f.c
- pam_u2f.8.txt
add the pam_sm_setcred service function to pam-u2f. Fedora 21 calls this function after a successful authentication. Not sure why this happens but a similar function is also in pam_yubico.
> added pam_sm_setcred service function

- README
Add libpam to dependencies and allso `--no-install-recommends` so that users don't accidentally install an extra GB of packages.
> Add libpam to dependencies in readme

- README
- pam-u2f.c
- pam_u2f.8.txt
- util.c
- util.h
Besides "interactive" this one adds a new manual mode where the challenges are printed on screen and responses retrieved via keyboard, which facilitates debugging and also enables a makeshift for SSH authentication (along with a patched libu2f-host which allows 'pam://' origins).
This patch also includes interactive mode, implemented using `pam_get_item`. Although the other patch I submitted would work as well by `printf`, `pam_get_item` is better for its portability.
> Manual mode & interactive

- README
- pam-u2f.c
- util.c
- util.h
Hi,
I have login and desktop manager use pam-u2f in required mode, but for sudo I use the module in sufficient mode. With sudo i regularly waited for the prompt for my password forgetting i had the key attached, so i added the cue to tell me to push the button.
I've tried to keep the code standards consistent.
Kind Regards,
Mike
> cue: a reminder to push the yubikey button

- pam-u2f.c
- util.c
This patch fixes the following issues on OS X.
```
$ make
Making all in .
CC       pam-u2f.lo
pam-u2f.c:147:19: error: use of undeclared identifier 'errno'
strerror(errno)));
^
pam-u2f.c:67:36: note: expanded from macro 'DBG'
#define DBG(x) if (cfg->debug) { D(x); }
^
./util.h:28:12: note: expanded from macro 'D'
printf x;                                                         \
^
1 error generated.
make[1]: *** [pam-u2f.lo] Error 1
12 /*
make: *** [all-recursive] Error 1
```
```
$ make
Making all in .
CC       pam-u2f.lo
CC       util.lo
util.c:33:58: error: use of undeclared identifier 'errno'
D(("Cannot open file: %s (%s)", authfile, strerror(errno)));
^
./util.h:28:12: note: expanded from macro 'D'
printf x;                                                         \
^
util.c:39:58: …
```
> Fix build issues on OS X

- pamu2fcfg/pamu2fcfg.c
It was tagged as `gethostname()`.
> Properly tag `perror()` call for `getlogin()`.

- pamu2fcfg/pamu2fcfg.c
I encountered a problem with `getlogin` failing like so:
$ pamu2fcfg
getlogin: No such file or directory
So I decided to investigate, [this StackOverflow answer](http://stackoverflow.com/questions/4785126/getlogin-c-function-returns-null-and-error-no-such-file-or-directory/4785195#4785195) informed me that `getlogin` was deprecated because of [the fact that it relies on a valid UTMP file](http://stackoverflow.com/questions/4785126/getlogin-c-function-returns-null-and-error-no-such-file-or-directory/4785186#4785186), which I didn't have apparently.
So I replaced `getlogin` with `getpwuid(getuid())` which returns a `struct passwd` (the `passwd` file entry for the current user) that I then use to get the username. Just a quick fix, tried and tested on my machine, hope it helps.
> Replaced getlogin with getuid and getpwuid to obtain username

- util.c
When debugging the PAM module, its useful to have the underlying
u2f libraries emit debugging information as well.
Fixes #43
> util, auth: Pass debug down to the u2f libs.

- README
- man/pam_u2f.8.txt
- pam-u2f.c
- util.h
As mentioned in the doc change, this is necessary to support pam-u2f on NFS homes with root_squash.
> Add openasuser option

- util.c
Hello,
While deploying pam-u2f we looked at get_devices_from_authfile() which handles untrusted data (with the default authfile setting users control the file) and noticed several issues. With the help of AFL we identified invalid memory access and memory leaks. This patch sets fixes these issues and performs a minor code cleanup for the error handling.
Due to lack of experience we didn't fuzz the USB part of the code which also handles untrusted input, but we think it would be a good way to further harden pam-u2f.
Regards
Simon
> Fix invalid memory access and memory leaks in get_devices_from_authfile

- util.c
- util.h
The original code would emit the "Please touch the device," string if configured by the cue command if any U2F token was inserted instead of doing so only upon finding a U2F token that is actually configured in the system. It does so by coercing the libu2f-host library to send a "check-only" authentication request to the attached tokens (0x7 control byte of this[0] spec).
In the PAM mantra of, "the user should know nothing about which module failed," emitting this message early leaks information about the system. Admittedly, the delay introduced with the extra interrogation also leaks information, and a malicious u2f key could record the keyhandle for off-line interrogation of keys, but at the very least, this avoids confusing users by not emitting the cue if no suitable key is inserted. …
> Avoid cueing user if no suitable U2F device is available.

- pam-u2f.c
- util.c
- util.h
Apparently I created a bug causing a segfault in applications that already have syslog opened, which many that do authentication will have, if dumping debug to syslog as well--I'm not sure exactly where it comes from, but my hunch is that the address of the string constant goes out of scope when the .so is unloaded.
> Fixes syslog crash in some applications

- README
- man/pam_u2f.8.txt
- pam-u2f.c
- util.h
Feedback on the code is very welcome!
This code has one functional issue where I hope you could give me a hint. I'll explain the scenario:
1. Open terminal 1, type `sudo -s`, do not touch the device.
* "Please touch the device" appears and stays on the screen as expected.
* The marker file is created as expected.
2. Open terminal 2, type `sudo -s`, do not touch the device.
* "Please touch the device" appears and stays on the screen as expected.
* On the terminal 1, the wait for touch is cancelled, I see a password prompt there - as expected.
* The marker file does not exist - **not expected**.
This is a race condition, in two terminals the code has reached the line where I create a marker file, but as soon as the first terminal aborts its waiting, it removes the file without accounting …
> Signify that pam-u2f is waiting for a touch

- README
- man/pam_u2f.8.txt
- pam-u2f.c
- util.c
- util.h
This is just like your `safecue` but fully documented and explained, and separated entirely from the `cue` option.
> Adds "nodetect" option to skip detection of suitable key

- util.c
If the size of string to log was bigger than BUFSIZE we use malloc
but if malloc fails we should try and handle it gracefully by
logging that we failed to allocate instead of segfaulting.
> Handle malloc failing when logging

- util.c
Fixes a one byte heap overwrite if called with a large buffer.
Consider the follow scenario:
size = (unsigned int)snprintf(NULL, 0, DEBUG_STR, file, line, func);
va_start(ap, fmt);
size += (unsigned int)vsnprintf(NULL, 0, fmt, ap);
Size now contains length but without counting the \0
out = malloc(size);
No room allocated for the terminating \0
if (out) {
size = (unsigned int)sprintf(out, DEBUG_STR, file, line, func);
vsprintf(&out[size], fmt, ap);
va_end(ap);
}
vsprintf will terminate the out buffer with a \0 outside of the allocated area.
Tested on Linux with debug set to stderr, a file and syslog
> Switch to using vsyslog/vfprintf in the linux case as well

- README
- pam-u2f.c
When a debug_file is specified but not yet created pam-u2f would not create and not log to the debug_file consequently. Amend this.
> DBG mode: debug_file missing

- util.c
Fix an issue with `nodetect` and non-resident credentials.
Closes #161
> Do not error out when nodetect is set and devices are found

- .github/workflows/linux_fuzz.yml
- .gitignore
- build-aux/ci/fuzz-linux-asan.sh
- configure.ac
- fuzz/Makefile.am
- fuzz/coverage.sh
- fuzz/fuzz_format_parsers.c
- fuzz/make_seed.py
With this harness we get good coverage in the format parsing code.
The fuzzer will also run on every push and pull request, using the corpus I have generated and stored in a google cloud bucket which exercises most code paths in the format parsers.  Further harnesses can be added later to get more coverage.
Do you think this can be added to the repo?
```
$ llvm-cov report -show-functions -instr-profile=default.profdata fuzz_format_parsers ../*.c
File '/user/kode/pam-u2f/b64.c':
Name                        Regions    Miss   Cover     Lines    Miss   Cover
-----------------------------------------------------------------------------
b64_encode                       33       5  84.85%        48       2  95.83%
b64_decode                       27       4  85.19%        48       1  97.92% …
```
> Add fuzzing harness for fuzzing native and ssh formats

- b64.c
- util.c
UCHAR_MAX and INT_MAX are defined within limits.h
Current codebase failed to be built in Linux with musl libc due to
missing this inclusion.
Fix it.
> b64,util: always include limits.h

- .github/workflows/scan.yml
Seems Github images dropped this by default so we now need to explicitly install it.
> actions: add xsltproc as dependency

- pamu2fcfg/pamu2fcfg.c
Fixes https://github.com/trezor/trezor-firmware/issues/1366. Tested by @prusnak.
This PR adds support for [self attestation](https://www.w3.org/TR/webauthn/#self-attestation) in pamu2fcfg, which was implemented in libfido2 about a year ago (v1.3.0) as a result of https://github.com/Yubico/libfido2/issues/57.
> Support self-attestation in pamu2fcfg

- README
Updated the link to the Authorization Mapping Files docs from `files` to `authMappingFiles`, as the current link links to `#files` which is a HTML div used by GitHub, thus breaking the desired functionality of this link.
> README: update Authorization Mapping Files link

- util.c
- Handle converse() returning NULL;
- Check that the UV bit is set in fido_assert_verify().
> Fix for #175 + related fix

- Makefile.am
- configure.ac
- fuzz/Makefile.am
This uses the `COMPILER_CLANG` conditional to add the `fuzz/` subdir. Otherwise, the directory is not included in the tarball created by `make dist`. If one then tries to build from the tarball with `CC=clang`, then `./configure` fails with
```
config.status: error: cannot find input file: `fuzz/Makefile.in'
```
> dist: make tarball configure/build with CC=clang 

- pamu2fcfg/pamu2fcfg.c
First step in an attempt of reducing scopes in pamu2fcfg. While here, refactor the main function to always explicitly cleanup allocated memory and close any potentially open device.
> pamu2fcfg: introduce print_authfile_line()

- configure.ac
- pamu2fcfg/Makefile.am
- pamu2fcfg/openbsd-compat.h
- pamu2fcfg/pamu2fcfg.c
- pamu2fcfg/strlcpy.c
Split parts of `main()` into `{prepare,make,verify}_cred()`.
> pamu2fcfg: introduce {prepare,make,verify}_cred()

- configure.ac
By default, clang only warns for unknown warnings. This makes the
AX_CHECK_COMPILE_FLAG macro always include the flags, regardless whether
they are supported. To remedy, add -Werror=unknown-warning-option during check.
> make: improve checks for compiler warnings under clang

- Makefile.am
* Without `DESTDIR`, `make install` will try to delete files from the live filesystem.
* Also, do not change `libdir`, create a separate prefix for the pam plugin instead.
> respect `DESTDIR`

- util.c
- util.h
While here, also drop an unused attribute in the `cfg_t` struct.
> util: plug memory leak

- pamu2fcfg/pamu2fcfg.c
- util.c
- util.h
While here, also introduce set of helper functions for managing the public keys in the service module.
Note, EDDSA support only implemented for the native format and not the SSH format.
> pamu2fcfg, util: add support for EDDSA

- util.c
- util.h
... and fixup the only resulting compiler warning.
> util: decorate _debug with the format attribute

- README
- man/pamu2fcfg.1.txt
- pamu2fcfg/cmdline.ggo
- pamu2fcfg/pamu2fcfg.c
- util.c
- util.h
Apart from the title, this also
- ~introduces a couple of helpers to with the SSH key parsing,~ (introduced separately in #201)
- fixes a regression in pamu2fcfg argument parsing that slipped by in #199,
- and updates documentation to include native/ssh EDDSA support
> util: add support for ed25519-sk

- build-aux/ci/fuzz-linux-asan.sh
Split corpus into subfolders while we keep `fuzz_format_parsers` around.
https://github.com/Yubico/pam-u2f/pull/208/checks?check_run_id=3075770515#step:4:1012
```
+ fuzz/fuzz_format_parsers corpus/format_parsers -reload=30 -print_pcs=1 -print_funcs=30 -timeout=10 -runs=1
INFO: Seed: 557801670
INFO: Loaded 2 modules   (3872 inline 8-bit counters): 2507 [0x7f59bf768c70, 0x7f59bf76963b), 1365 [0x5de950, 0x5deea5), 
INFO: Loaded 2 PC tables (3872 PCs): 2507 [0x7f59bf769640,0x7f59bf7732f0), 1365 [0x596590,0x59bae0), 
INFO:      293 files found in corpus/format_parsers
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 293 min: 1b max: 2561b total: 55110b rss: 30Mb
#295	INITED cov: 216 ft: 665 corp: 249/44Kb exec/s: 0 rss: 43Mb …
```
> ci: update fuzz corpus url and paths

- README
- man/pam_u2f.8.txt
- man/pamu2fcfg.1.txt
- pamu2fcfg/cmdline.ggo
Since pam-u2f/pamu2fcfg 1.1.0, these are the RP ID and RP name
respectively. This (together with #206) resolves #205.
> man: improve documentation on origin/appid

- .github/workflows/codeql-analysis.yml
- .github/workflows/linux_builds.yml
- .github/workflows/scan.yml
libfido2 has been updated to 1.8.0 and fixed its pkg-config file.
This reverts commit f704ec7ff92a84f7adfcf6564e4ff6ec26f3b19e.
> ci: revert workaround for libfido2 1.7.0 pkg-config

- pam-u2f.c
Reduces scope of helper variable required to free the user response.
> pam: add helper function for `interactive` prompt

- Makefile.am
- debug.c
- debug.h
- pam-u2f.c
- util.c
- util.h
Move debug-related functions here and introduce `debug_dbg()` which can be
used to replace if-debug-debug constructs.
> debug: introduce debug.{c,h}

- configure.ac
- m4/ax_check_compile_flag.m4
- AC_PROG_CC_STDC was integrated into AC_PROG_CC in autoconf 2.54.
- Replace only remaining occurrence of obsolete AC_HELP_STRING.
- Modern libtool prefers passing options through LT_INIT.
- Update ax_check_compile_flag to the latest revision (AC_TRY_LINK is obsolete).
> autoconf: fix warnings about obsoleted macros

- README
- build-aux/ci/build-osx.sh
- build-aux/ci/fuzz-linux-asan.sh
the unauthenticated git protocol on port 9418 (git://) is no longer supported by github.
> git -> https

- Makefile.am
- configure.ac
- man/Makefile.am
- pamu2fcfg/Makefile.am
`DISTCLEANFILES` is replaced with `MAINTAINERCLEANFILES`, the former is
primarily intended for files generated by `configure`. We are
distributing the generated man pages as if they were source files.
> man: collect man page generation rules

- pamu2fcfg/Makefile.am
Running make in parallel would spawn two instances of gengetopt. To
prevent this, use a GNU make pattern rule which is able to express rules
with multiple output files. Other make implementations should still be
able to build from the tarballs. While here, remove an unnecessary
include path.
> pamu2fcfg: prevent parallel generation of cmdline.[ch]

- pam-u2f.c
- util.h
Use a single `asprintf()` call towards the end of `resolve_authfile_path()`. While here, ensure that the resolved path is absolute.
> pam: reduce `asprintf` repetition

- tests/get_devices.c
- tests/regenerate_credentials.py
- only regenerate credentials if templates are missing (otherwise read the templates),
- split manually written and auto-generated tests to separate functions.
> tests: separate manually written and generated test cases

- fuzz/export.sym
- fuzz/fuzz_auth.c
- fuzz/fuzz_format_parsers.c
Have `fuzz_format_parsers` use this function instead of the two private
authfile parsers. This is made possible via the mocking utilities
introduced along with `fuzz_auth` and enables us to not have to include
the relevant sources directly in the fuzzer harness source.
> fuzz: export get_devices_from_authfile() 

- configure.ac
When we bump up the minimum libfido2 version to >=1.9.0 we can switch to
using the EVP interface rather than the deprecated EC_KEY interface.
Until then, silence the related deprecation warnings.
> make: silence deprecation warnings for OSSL 3.*

- README
- man/pam_u2f.8.txt
Explicitly state YubiKey 4 series does not support asking for pin.
__Problem__
* FIDO(1) devices are only partially supported. They can be used as a second authentication factor to the password or as a single factor by themselves, but they cannot be used in conjunction with a `pin`.
* The failure mode consists in silently ignoring the device.
It does not provide any feedback as to why the authentication procedure is failing and it's thus very complicated to debug (see for example #144).
* YubiKey product pages, understandably, do not highlight the differences between FIDO and FIDO2, users may thus not realize at a first glance what their devices do actually support.
__This PR__
Add a paragraph to help users like myself understand why their YubiKeys work only half of the time.
__Next …
> FAQ: YubiKey 4 does not support asking for pin

- man/pamu2fcfg.1.txt
`--username` and `--nouser` are no longer mutually exclusive as they serve different purposes.
> man: sync manpages with pamu2fcfg help text

- .github/workflows/alpine_builds.yml
- tests/get_devices.c
`$USER` may not be set, look up the username of the effective user ID
from the password database instead. In the long term, consider splitting
authfile handling and parsing to simplify testing.
> tests: prefer getpwuid over getenv

- README
- man/pamu2fcfg.1.txt
- pamu2fcfg/pamu2fcfg.c
Perform basic sanity checking of the user's selected authentication UV options and exercise chosen UV method(s) on credential creation. This fixes #278.
> pamu2fcfg: sanity check UV options

- COPYING
- Makefile.am
- README
- expand.c
- man/pam_u2f.8.txt
- pam-u2f.c
- tests/Makefile.am
- tests/expand.c
- util.h
Add a toggle for enabling variable expansion in the authfile path. Accepted variables are `%u` (replaced with the value of `PAM_USER`) and `%%` (replaced with a `%`), any other variable will cause the module to return an error. Variable expansion is performed before any default or relative paths are resolved.
Resolves #218.
> pam: add opt-in for %u expansion in authfile path

- man/pam_u2f.8.txt
Leftover references to a "central" authfile; which the man page otherwise does not cover.
> man: clarify relative and absolute authfile paths

- .github/workflows/codeql-analysis.yml
- .github/workflows/macos_builds.yml
- build-aux/ci/build-osx.sh
`brew` has for some time packaged libfido2. We can use those builds to
simplify our pipeline. Ensure linking to the same OpenSSL version as
libfido2 through `brew deps`.
While here, fix CodeQL workflow permissions.
> ci: simplify macos build, fix codeql workflow

- pam-u2f.c
This fixes two minor grammatical errors in debug messages in _pam-u2f.c_ and rephrases another make it more clear what produced the error.
> Fix grammatical errors & rephrase a debug message

- pamu2fcfg/pamu2fcfg.c
- util.c
- util.h
* Add preprocessor constant `DEVLIST_ALLOC_INITIAL_LEN` to replace magic number 64 in allocations of device info list. The named constant expresses meaning and makes bugs & memory-leaks due to missed code changes less likely, should one decide to change the number of slots to allocate in the device info list.
* Fix the same errorneous code in freeing the device info list at three points in the code:
Calling `fido_dev_info_free` with length argument `ndevs` deallocates only the filled entries of the device info list, while leaving the empty entries dangling. This does not seem to leak any data, though.
The commit fixes the code to actually deallocate the whole array.
> Fix (harmless) memory leaks & replace magic number with constant

- .github/workflows/macos_builds.yml
The macos-12 runner is deprecated; macos-15 is in public preview.
> ci: rotate out macos-12, bring in macos-15

- fuzz/fuzz_auth.c
- fuzz/wrap.c
A few changes I think would improve fuzzing :)
> Fuzzer mods

- expand.c
- util.c
The `-Wsign-conversion` warning is currently disabled in pam_u2f, due to a conflicting macro in `security/pam_modutil.h` (`PAM_MODUTIL_DEF_PRIVS`). This setting shadowed a couple of warnings, which have been noticed while working on the build system.
> Fix sign conversion warnings

- .gitignore
- Makefile.am
- README
- cfg.c
- cfg.h
- configure.ac
- fuzz/Makefile.am
- fuzz/export.sym
- fuzz/fuzz.h
- fuzz/fuzz_auth.c
- fuzz/wrap.c
- man/Makefile.am
- man/pam_u2f.8.txt
- pam-u2f.c
- tests/Makefile.am
- tests/cfg.c
- util.h
> Config file support

- tests/Makefile.am
- tests/get_devices.c
```
pam-u2f_public $ git grep strlcpy
configure.ac:AC_CHECK_FUNCS([secure_getenv strlcpy readpassphrase explicit_bzero memset_s])
fuzz/fuzz_auth.c:  /* FIXME: use strlcpy */
pamu2fcfg/Makefile.am:pamu2fcfg_SOURCES += strlcpy.c openbsd-compat.h
pamu2fcfg/openbsd-compat.h:size_t strlcpy(char *, const char *, size_t);
pamu2fcfg/pamu2fcfg.c:    if (strlcpy(origin, args->origin, sizeof(origin)) >= sizeof(origin)) {
pamu2fcfg/pamu2fcfg.c:      fprintf(stderr, "error: strlcpy failed\n");
pamu2fcfg/pamu2fcfg.c:    if ((n = strlcpy(origin, PAM_PREFIX, sizeof(origin))) >= sizeof(origin)) {
pamu2fcfg/pamu2fcfg.c:      fprintf(stderr, "error: strlcpy failed\n");
pamu2fcfg/strlcpy.c:/*  $OpenBSD: strlcpy.c,v 1.11 2006/05/05 15:27:38 millert Exp $    */
pamu2fcfg/strlcpy.c:/* OPENBSD ORIGINAL: …
```
> Remove spurious dependency

- .github/workflows/check-commit-hooks.yml
- build-aux/ci/check-commit-hooks
- contrib/allowed-trailers.txt
- contrib/gen-news
- contrib/hooks-setup
- contrib/hooks/commit-msg
We are leveraging git trailers to automate the additions to the NEWS file during release.
Commits having the `Changelog` trailers are checked automatically, to enforce the use of a restricted set of values.
The checks can be used as commit hooks during development.  They're compatible by design.
> Git trailers

- cmake/FindPAM.cmake
As it turns out, the cmake version shipped with ubuntu 24.04 can not correctly handle ALIAS targets as CMAKE_REQUIRED_LIBRARIES.
We didn't realize before because the ubuntu 24.04 vm available for github actions ships another version of cmake, (3.31.5 instead of 3.28)
> Work-around cmake bug

- README
- cfg.c
- cfg.h
- debug.c
- debug.h
- fuzz/fuzz_auth.c
- man/pam_u2f.8.txt
- tests/Makefile.am
- tests/cfg.c
- tests/get_devices.c
- tests/mock_syslog.c
- util.c
We are removing the `debug_file=` option, both from the pam_u2f.so arguments and configuration.
The module loses the ability to send debug info towards a file or stdout. It is still possible to log on stderr via syslog, e.g.
```c
openlog(argv[0], LOG_PERROR, 0);
```
This is a breaking change, so it is targeting the `next` branch instead of `main`, meaning that these change will flow into the first scheduled _major bump_.
> Remove debug_file=

- CMakeLists.txt
- Makefile.am
- cfg.c
- expand.c
- fuzz/fuzz_format_parsers.c
- fuzz/wrap.c
- logging.c
- logging.h
- pam-u2f.c
- tests/Makefile.am
- tests/get_devices.c
- util.c
- util.h
Now that the `debug_file=` option has been removed, and logging is only sent to syslog, we can make use of log levels.
The `debug` module is renamed as `logging`, and the `dbg_debug` call is replaced with `LOG(Level, ...)`.
The configuration (`cfg_t` object) is no longer necessary in a number of functions, since it was only required as argument for the `dbg_debug` call.
> Rework debug into full syslog wrapper

- README
- man/pam_u2f.8.txt
- pamu2fcfg/pamu2fcfg.c
- util.c
- util.h
Change references to "devices" / "authenticators" / "tokens" to "FIDO authenticator".
The change affects only user prompts, README and manpages, while log lines are kept as they are, at least for now.
> Terminology updates

- fuzz/CMakeLists.txt
This fixes the following warning by libfuzzer:
WARNING: no interesting inputs were found so far. Is the code instrumented
for coverage?
> fuzz: Add missing compile options

- .github/workflows/linux_builds.yml
Will be removed by GitHub 2025-04-01.
> ci: drop ubuntu 20.04 runners
