Yubico/pam-u2f

- pam-u2f.c
> pam-u2f.c: Define _GNU_SOURCE to make secure_getenv(3) available

- README
> README: Add blurb on appid/origin on dynamic networks.

- Makefile.am
- configure.ac
- pamu2fcfg/Makefile.am
> Add knob to disable man page generation

- README
- man/pam_u2f.8.txt
- pam-u2f.c
- util.h
Addressed documentation/simplification parts pointed out by @a-dma
> Updates to #48

- pam-u2f.c
> Simplify nouserok checks for missing/malformed authfiles

- configure.ac
- pam-u2f.c
- util.c
Hi,
I noticed a few minor issues while looking through the code. Only a few of them are bugs but I think the resulting code is easier to read and more future-proof.
There is one patch which potentially changes the behavior (2af1f4c), please check if this is acceptable.
Regards
Simon
> Minor code cleanup

- README
- man/pam_u2f.8.txt
- pam-u2f.c
- util.c
- util.h
Adds a syslog option to debug_file for debugging when you don't have access to stderr or stdout.
> Adds syslog option to debug_file

- README
Several github issues for this repo would be resolved by updating the instructions to just include: pkg-config libu2f-host-dev libu2f-server-dev
> Update common github repo dependency questions

- util.c
I promise I'll eventually stop writing bugs into your code.
> Fixes nodetect debug output.

- README
- man/pam_u2f.8.txt
- pam-u2f.c
- util.c
- util.h
Any other suggestions for the option name?
> Add "cue_prompt" option to set text shown with cue

- README
- man/pam_u2f.8.txt
Signed-off-by: corbolais <corbolais@gmail.com>
> Clarify usage of individual user mapping file.

- .github/workflows/scan.yml
o Point to documentation for the scanner
o Use continue-on-error: true instead of || true
> Re-schedule scans every week

- README
- man/pam_u2f.8.txt
> man: clarify authfile path, update authfile format

- .github/workflows/alpine_builds.yml
- tests/get_devices.c
- tests/regenerate_credentials.py
Fix sizeof of incorrect type while here, detected by failing musl builds.
> ci: add musl build

- util.c
If the user specifies PIN or user verification, only proceed with CTAP2
authenticators that support these modes. Moreover, if user verification
is disabled and unsupported by the authenticator, omit the option
instead of explicitly specifying it (as per spec).
This can be simplified when we can enforce libfido2 1.7.0 or greater
using the `fido_dev_{supports,has}_{pin,uv}` family of functions.
This resolves #183.
> util: filter authenticators based on selected options

- .github/workflows/linux_builds.yml
- Makefile.am
- build-aux/ci/distcheck.sh
While here, have the Linux CI also run distcheck.
> misc: improve support for distcheck/DESTDIR

- pam-u2f.c
Given a relative or unassigned authfile path, this function allocates
and returns the absolute path to the authfile.
> pam: add helper function to resolve `authfile` path

- pam-u2f.c
Initial batch of D() (and DBG()) replacements.
> pam: switch over to debug_dbg()

- tests/regenerate_credentials.py
While here, reduce some repetition via a helper function (no functional change).
> tests: modernize regenerate_credentials.py

- util.c
extracts (native) credential components from a comma-delimited list
> pam: introduce parse_native_credential() 

- .github/workflows/alpine_builds.yml
also bump the host OS and install (potentially) missing bash
> ci: simplify alpine workflows

- README
Sync from `Building from Git` section.
> Updated README to add source acquisition instructions  in 'Building' section

- .github/workflows/codeql-analysis.yml
CodeQL action v2 will be deprecated on 2024-12-05.
> ci: update CodeQL

- configure.ac
I doubt this was ever a problem... let's fix it anyway.
> configure.ac: fix -W{ => sign-}conversion

- .github/workflows/linux_fuzz.yml
- build-aux/ci/fuzz-linux-asan.sh
This change enables the developer to generate have multiple runs of the fuzzing, and to generate the reports
> Fuzzing script improvements
